version: "3"
services: 
    api:
        container_name: "my-api"
        ports: 
          - "5000:5000"
        build: .
        volumes: 
          - .:/app
        restart: on-failure
        command: "python main.py"
    mongodb:
        container_name: my_mongo
        volumes:
            - ./db/mongo:/data/db
        image: mongo:4.0
        
    redis:
        container_name: my_redis
        image: redis:5

    nginx:
      container_name: nginx
      build: ./nginx
      ports: 
        - "80:80"